### PR TITLE
fix: wrong parsing of a spending condition tx

### LINKED ISSUE #184: startExit fails for spending condition output
Trying to `startExit` with youngestInputIndex > 0 fails (wrong parsing?)

## Scope
- reproduce bug with the unit test. Use [integration test](https://github.com/leapdao/integration-tests/blob/27a3356ef640a6cda04fef580fab67c63de4817d/tests/8_breeding.js#L176) as an example
- fix the bug
- remove the workaround from integration tests

## Deliverables
- updated code 
- updated unit tests

## Gain for the project

People can exit their UTXOs!

## Roles
gardener: @troggy + @pinkiebell  / 50 DAI
worker: @troggy / 85% / 240 DAI
reviewer: @johannbarbie  / 15% / 60 DAI

## Funded by

Dev Circle

### PR DESCRIPTION
**Pull request by troggy**
Resolves #184 

## Preface

The first input of a spending condition transaction is special.
It has two additional attributes:
- `script` with a bytecode of <accr title="spending condition">spendie</accr>
- `msgData` with a bytecode for msgData of a function call (called on spendie contract)

To account for that, we have a special code for parsing transaction ([contracts](https://github.com/leapdao/leap-contracts/blob/master/contracts/TxLib.sol#L69), [client](https://github.com/leapdao/leap-core/blob/c2c30fb2fe89da6a1d02744c6afd828a1acbc7c5/lib/input.js#L216).

## What was wrong

The thing is that it is only the first input of spendie is special, all the other inputs are the ordinary inputs and should be parsed as ordinary. That wasn't the case, solidity parser incorrectly tried to parse all the spendie inputs as the first one.

## The fix

- Use special parsing only for the first input of spendie [here](https://github.com/leapdao/leap-contracts/commit/a959bdc6ca59e971bff164bf701a31b5dc4ae864#diff-a4e8014fa0cb2ad3a5c650aa58b1883dR196)
- Use more realistic test data in tests [here](https://github.com/leapdao/leap-contracts/commit/a959bdc6ca59e971bff164bf701a31b5dc4ae864#diff-1675070299835c72d9963e9350b24a66R278). No script, no msgData for the rest of the inputs. Sign the tx. This change alone would make the tests fail because of incorrect parsing
- fix couple of errors in the unit tests making the test not working [here](https://github.com/leapdao/leap-contracts/pull/252/commits/30d9687776a136be869a0aaa629ee8e5a5a124b0) and [there](https://github.com/leapdao/leap-contracts/pull/252/commits/9eaae0b54a2c1e05ac2b6fd250caf1a752cdde4c).
- remove workaround from the integration tests: https://github.com/leapdao/integration-tests/pull/71

### CODE REVIEW

File: test/exitHandler.js [hunk 1]
```diff
@@ -131,12 +131,37 @@ contract('ExitHandler', (accounts) => {
 
     describe('Start exit', async () => {
       it('Should allow to exit valid utxo', async () => {
-        const period = await submitNewPeriod([depositTx, transferTx]);
+        const period1 = await submitNewPeriod([depositTx, transferTx]);
```
Comment (troggy) [inline test/exitHandler.js]: this change (the whole change in `exitHandler.js`) appears to be not relevant for the fix. I keep it here, because it is a good test 😆
