### PR TITLE
Fix gas errors in `truffle migrate`

### LINKED ISSUE #153: migration fails on estimateGas
Executing

```
DEPLOYED_TOKEN=0xD2D0F8a6ADfF16C2098101087f9548465EC96C98 PROPOSAL_TIME=0 yarn deploy --network rinkeby --reset
```

**Result:**

```

yarn run v1.13.0
$ truffle migrate --network rinkeby --reset
⚠️  Important ⚠️
If you're using an HDWalletProvider, it must be Web3 1.0 enabled or your migration will hang.


Starting migrations...
======================
> Network name:    'rinkeby'
> Network id:      4
> Block gas limit: 8000000


1_initial_migration.js
======================
gas required exceeds allowance or always failing transaction
Truffle v5.0.3 (core: 5.0.3)
Node v8.15.0
error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
```

fails on call to `Migrations.new.estimateGas()`

### PR DESCRIPTION
**Pull request by pinkiebell**
- increase the gasLimit to 1 million for both mainnet & rinkeby
- set a gasPrice of 3 Gwei for rinkeby

Fixes #153

### CODE REVIEW

**Comment by johannbarbie** [comment]
setting each tx to 1,000,000 on mainnet has some disadvantages:
- you need a lot of funds on the key
- transactions are mined much slower, hence whole deployment takes x hours

**Comment by pinkiebell** [comment]
> setting each tx to 1,000,000 on mainnet has some disadvantages:
> 
> * you need a lot of funds on the key

The goerli deployment was done with something about ~0.2 ETH 🤷‍♂️ 

> * transactions are mined much slower, hence whole deployment takes x hours

What does the gasLimit have to do with mining time? 🙂

**Comment by johannbarbie** [comment]
> What does the gasLimit have to do with mining time? 🙂

i guess it is harder to fit in a big transaction that is low/medium prices. I'm only summing up my experience when i tried to deploy production for 6+ hours.

**Comment by pinkiebell** [comment]
Ops, this is not fixing:
```
   Deploying 'FastExitHandler'
   ---------------------------
   > transaction hash:    0x8fb668af3d679e77c5abd31ba782c7e47837ec5f4c4912f42cca6edf3203d61a
   > Blocks: 2            Seconds: 32
   > contract address:    0xbE8ed8CFFD01350BFFDf62230bC5368B9D185a0a
   > account:             0x9D4F8216808F7dFbB919cF5e579c1894a1E197C3
   > balance:             0.125539574990340506
   > gas used:            5147867
   > gas price:           1 gwei
   > value sent:          0 ETH
   > total cost:          0.005147867 ETH
```
I guess we have to set the gasLimit to ~6million

**Comment by johannbarbie** [comment]
> gasLimit to ~6million
that configuration will not work for mainnet at all

**Comment by johannbarbie** [comment]
ideally you want to have a per tx estimate of gas

**Comment by pinkiebell** [comment]
> ideally you want to have a per tx estimate of gas

We already use some estimates in `migrations/` that will override the truffle-config,
but it complains if your gasLimit in `truffle-config` is lower :)

**Comment by johannbarbie** [comment]
> We already use some estimates in `migrations/` that will override the truffle-config,

ah, so we are keeping those?

> but it complains if your gasLimit in `truffle-config` is lower :)

why not add estimates to all the txns?

**Comment by pinkiebell** [comment]
> > We already use some estimates in `migrations/` that will override the truffle-config,
> 
> ah, so we are keeping those?

Yep

> 
> > but it complains if your gasLimit in `truffle-config` is lower :)
> 
> why not add estimates to all the txns?

Sure, can do.

**Comment by pinkiebell** [comment]
@johannbarbie 
Done. Tested and works 🙂

**Comment by pinkiebell** [comment]
> 🌮

🍴

File: truffle-config.js [hunk 1]
```diff
@@ -34,15 +34,19 @@ module.exports = {
...
       gasPrice: 5000000000 // Specified in Wei
     },
     rinkeby: {
       provider: () => new HDWalletProvider(
         process.env.RINKEBY_MNEMONIC, 'https://rinkeby.infura.io', 0, 2,
       ),
       network_id: '4',
-      gas: 200000
+      // hard gas limit
+      gas: 6000000,
```
Comment (troggy) [inline truffle-config.js]: Isn't having such a limit here makes all the individual estimates not necessary?

Comment (pinkiebell) [reply truffle-config.js]: truffle complaints if these are not there. Maybe a safety measure 🤷‍♂️

Comment (troggy) [reply truffle-config.js]: What's the complain?

To illustrate my point: https://github.com/leapdao/leap-contracts/pull/157/
This works for me for ganache and rinkeby without any hardcoded estimates.

Reduced gas limit to 5.5m because we don't have larger txs

Comment (pinkiebell) [reply truffle-config.js]: @troggy Course it works, because that PR will set a gas limit to 5.5 mil for every transaction.
@johannbarbie mentioned that this will take longer to mine tho. 🤷‍♂️ 
I don't have experience on this part 🙂
